// Generated by CoffeeScript 1.4.0
(function() {
  var app, express, superagent, tally;

  express = require('express');

  tally = require('./lib/tally-express.coffee');

  superagent = require('superagent');

  app = express();

  app.engine('html', tally.__express);

  app.set('views', __dirname + '/views');

  app.use(express["static"]('views'));

  app.get('/simple', require('./simple.coffee').simple);

  app.get('/posts', function(request, response) {
    return superagent.get('https://alpha-api.app.net/stream/0/posts/stream/global').end(function(globalTimelineResponse) {
      if (globalTimelineResponse.body) {
        globalTimelineResponse.body.numberOfPosts = function() {
          return this.data.length;
        };
        return response.render('posts.html', globalTimelineResponse.body);
      } else {
        return response.render('posts.html', {
          error: 'Bad response from Twitter'
        });
      }
    });
  });

  app.get('/profile', require('./profile.coffee').profile);

  app.listen(3000);

  console.log('The Tally sample is listening on port 3000…');

}).call(this);
