// Generated by CoffeeScript 1.4.0
(function() {
  var fs, handlebars, jsdom, tally;

  jsdom = require('jsdom');

  fs = require('fs');

  handlebars = require('handlebars');

  tally = (fs.readFileSync(__dirname + '/tally.js', 'utf8')).toString();

  exports.__express = function(path, data, callback) {
    return fs.readFile(path, 'utf8', function(error, template) {
      var document, handleBarsTemplate, html, window;
      if (error) {
        return callback(error);
      }
      document = jsdom.jsdom(template, '2');
      window = document.createWindow();
      window.console = console;
      data.aralbalkan = {
        tallyRunningInNode: true
      };
      window.data = data;
      window.run(tally);
      window.tally.format['fullURL'] = function(value) {
        return 'http://' + value + '.com';
      };
      window.run('tally(window.document.documentElement, window.data);');
      html = window.document.innerHTML;
      if (data.hybrid === true) {
        console.log('Hybrid');
        handleBarsTemplate = handlebars.compile(html);
        html = handleBarsTemplate(data);
      }
      return callback(null, html);
    });
  };

}).call(this);
